services:
  - type: web
    name: rinok-server
    env: node
    buildCommand: cd server && npm install
    startCommand: cd server && npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      - key: TELEGRAM_BOT_TOKEN
        fromDatabase: false
      - key: TELEGRAM_CHAT_ID
        fromDatabase: false

  - type: web
    name: rinok-frontend
    env: static
    buildCommand: npm install && npm run build
    staticPublishPath: ./build
    routes:
      - type: rewrite
        source: /*
        destination: /index.html